// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqdu91ypVBecFvvb4PQdmlC02qk3Vet0A',
    appId: '1:437952879457:web:a5a0aaa15d720de78e0320',
    messagingSenderId: '437952879457',
    projectId: 'teste-f8ace',
    authDomain: 'teste-f8ace.firebaseapp.com',
    storageBucket: 'teste-f8ace.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWmVzcWgt3ITDi1gtJ4NdZer9g5Z7YYg',
    appId: '1:437952879457:android:1f40d8c575498f598e0320',
    messagingSenderId: '437952879457',
    projectId: 'teste-f8ace',
    storageBucket: 'teste-f8ace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqczVvc0oxQAP0vFiXJ0qPMIlRJ1fvRKU',
    appId: '1:437952879457:ios:37254a14d564d6d78e0320',
    messagingSenderId: '437952879457',
    projectId: 'teste-f8ace',
    storageBucket: 'teste-f8ace.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqczVvc0oxQAP0vFiXJ0qPMIlRJ1fvRKU',
    appId: '1:437952879457:ios:37254a14d564d6d78e0320',
    messagingSenderId: '437952879457',
    projectId: 'teste-f8ace',
    storageBucket: 'teste-f8ace.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqdu91ypVBecFvvb4PQdmlC02qk3Vet0A',
    appId: '1:437952879457:web:fd8d672cf1f6bb078e0320',
    messagingSenderId: '437952879457',
    projectId: 'teste-f8ace',
    authDomain: 'teste-f8ace.firebaseapp.com',
    storageBucket: 'teste-f8ace.firebasestorage.app',
  );
}
